version: '3.8'
name: "goshop"

services:
  mysql:
    image: mysql:latest
    container_name: goshop-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goshop
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
    mysql_data: