// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users(name, email) VALUES (?, ?)
`

type CreateUserParams struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser, arg.Name, arg.Email)
}

const getUser = `-- name: GetUser :one
SELECT user_id, uuid, name, email, created_at FROM users WHERE uuid = ?
`

func (q *Queries) GetUser(ctx context.Context, argUuid uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, argUuid)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Uuid,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
